name: Workflow aaplication streamlit

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Lint
        run: |
          pylint app.py --fail-under=0
      - name: Test Python code
        run: python app.py
        
  build:
    runs-on: ubuntu-latest

    needs: check
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set build number
        id: set_build_number
        run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ahmed577/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }} .
     
      - name: Push Docker image to Docker Hub
        run: |
          docker push ahmed577/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
   
    needs: build
   
    steps:

    - name: Set build number
      id: set_build_number
      run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"
     
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull ahmed577/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}
   
    - name: Stop and remove existing container
      run: |
        docker stop iris || true && docker rm iris || true
   
    - name: Run Docker container
      run: |
        docker run -d --name iris -p 8501:8501 ahmed577/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}
